import localSQLalchemy
from sqlalchemy import (
   BigInteger,
   Boolean,
   Column,
   Date,
   DateTime,
   ForeignKeyConstraint,
   Integer,
   LargeBinary,
   String,
   Table,
   Text,
   UniqueConstraint,
   text,
)


def get_table_schema(metadata):
   return Table(
      "contact",
      metadata,
      Column("userid", 
         BigInteger, 
         primary_key=True, 
         autoincrement=False
      ),
      Column("fullname", String(255), nullable=True),
      Column("givenname", String(50), nullable=False, index=True),
      Column("surname", String(255), nullable=True, index=True),
      Column(
         "createdate",
         DateTime,
         nullable=False,
         server_default=text("'0000-00-00 00:00:00'"),
      ),
      Column("modifydate", DateTime, nullable=True),
      Column("email", String(128), nullable=True),
      Column("options", Text, nullable=False),
      Column(
         "timezone", String(40), nullable=False, server_default=text("'CET'")
      ),
      Column("lang", String(10), nullable=True),
      Column("office_persnum", String(20), nullable=True),
      Column("office_elecfacsimile", String(80), nullable=True),
      Column("office_facsimile", String(80), nullable=True),
      Column("office_mobile", String(80), nullable=True),
      Column("office_phone", String(80), nullable=True),
      Column("office_street", String(80), nullable=True),
      Column("office_location", String(80), nullable=True, index=True),
      Column("office_zipcode", String(10), nullable=True),
      Column("private_elecfacsimile", String(80), nullable=True),
      Column("private_facsimile", String(80), nullable=True),
      Column("private_mobile", String(80), nullable=True),
      Column("private_phone", String(80), nullable=True),
      Column("private_street", String(80), nullable=True),
      Column("private_location", String(80), nullable=True, index=True),
      Column("private_zipcode", String(10), nullable=True),
      Column("posix_identifier", String(8), nullable=True),
      Column("picture", LargeBinary, nullable=True),
      Column("pagelimit", Integer, nullable=True, server_default=text("'20'")),
      Column(
         "cistatus",
         Integer,
         nullable=False,
         server_default=text("'0'"),
         index=True,
      ),
      Column("usertyp", 
         String(10), 
         nullable=True, 
         server_default=text("'user'")
      ),
      Column("comments", 
         String(65535),  # 64k
         nullable=True
      ),
      Column("ssh1publickey", 
         LargeBinary, 
         nullable=True
      ),
      Column("ssh2publickey",
         LargeBinary, 
         nullable=True
      ),
      Column("office_costcenter",
         String(20), 
         nullable=True, 
         index=True
      ),
      Column("office_accarea", String(20), nullable=True, index=True),
      Column("office_room", String(20), nullable=True),
      Column("secstate", Integer, nullable=True, server_default=text("'2'")),
      Column("formdata", Text, nullable=True),
      Column(
         "dialermode",
         String(20),
         nullable=True,
         server_default=text("'HTML-Dial-Tag'"),
      ),
      Column("dialerurl", String(128), nullable=True),
      Column("dialeripref", String(5), nullable=True),
      Column("gtctxt",
         String(65535),  # 64k
         nullable=True
      ),
      Column("gtcack", DateTime, nullable=True),
      Column("dateofbirth", DateTime, nullable=True),
      Column("persidentno", String(50), nullable=True),
      Column("driverlicno", String(50), nullable=True),
      Column("eurocarno", String(20), nullable=True),
      Column("sixtcarno", String(20), nullable=True),
      Column("dateofdatapriv", DateTime, nullable=True),
      Column("dateofdatapriv_edt", String(128), nullable=True),
      Column("dateofworksafty", DateTime, nullable=True),
      Column("dateofworksafty_edt", String(128), nullable=True),
      Column("dateofcorruprot", DateTime, nullable=True),
      Column("dateofcorruprot_edt", String(128), nullable=True),
      Column("dateofvsnfd", DateTime, nullable=True),
      Column("dateofvsnfd_edt", String(128), nullable=True),
      Column("dateofsecretpro", DateTime, nullable=True),
      Column("dateofsecretpro_edt", String(128), nullable=True),
      Column("killtimeout", 
         Integer, 
         nullable=True, 
         server_default=text("'1000'")
      ),
      Column("managedby", 
         BigInteger, 
         nullable=True, 
         server_default=text("'1'")
      ),
      Column("is_vsnfdsafe", 
         Boolean, 
         nullable=True,
         server_default=text("'0'")
      ),
      Column("admcomments", 
         Text, 
         nullable=True
      ),
      Column("ipacl", Text, nullable=True),
      Column("office_orgname", String(128), nullable=True),
      Column("salutation", String(2), nullable=True),
      Column("country", String(4), nullable=True),
      Column("banalprotect", Integer, nullable=True, server_default=text("'0'")),
      Column(
         "isw5support",
         Integer,
         nullable=True,
         server_default=text("'0'"),
         index=True,
      ),
      Column("pcontact", BigInteger, nullable=True, index=True),

      *localSQLalchemy.defaultSourceTableColumns(),

      Column("ds_identifier", String(128), nullable=True),
      Column("lastknownboss", String(128), nullable=True),
      Column("winhandling",
         String(20),
         nullable=True,
         server_default=text("'windefault'"),
      ),
      Column("lastexternalseen", Date, nullable=True),
      Column("lastknownpboss", String(128), nullable=True),
      Column("planneddismissaldate", DateTime, nullable=True),
      Column("notifieddismissaldate", DateTime, nullable=True),
      Column("office_sisnumber", String(20), nullable=True),
      Column("lorgchangedt", DateTime, nullable=True),
      Column("modifydate", DateTime, nullable=True),

      # --- Unique Constraints ---
      UniqueConstraint("fullname", 
         name="fullname"
      ),
      UniqueConstraint("posix_identifier", 
         name="posix_identifier"
      ),
      # --- Foreign Key Constraints ---
      ForeignKeyConstraint(
         ["pcontact"],
         ["contact.userid"],
         name="contact_ibfk_1",
         ondelete="CASCADE",
      ),
      extend_existing=True,
   )

