import localSQLalchemy
from sqlalchemy import (
   BigInteger,
   Column,
   DateTime,
   Index,
   Integer,
   LargeBinary,
   String,
   Table,
   Text,
   UniqueConstraint,
   text,
)


def get_table_schema(metadata):
   return Table(
      "grp",
      metadata,
      # --- Primary Key ---
      Column(
         "grpid",
         BigInteger,
         primary_key=True,
         autoincrement=False,
         server_default=text("'0'"),
      ),
      # --- Columns ---
      Column("parentid", BigInteger, nullable=True, index=True),
      Column("fullname", String(255), nullable=False, server_default=text("''")),
      Column("name", String(30), nullable=False, server_default=text("''")),
      Column(
         "cistatus",
         Integer,
         nullable=False,
         server_default=text("'0'"),
         index=True,
      ),
      Column("email", String(128), nullable=False, server_default=text("''")),
      Column("supervisor", BigInteger, nullable=False, server_default=text("'0'")),
      Column("srcsys", String(40), nullable=True),
      Column("srcid", String(128), nullable=True),
      Column("srcload", DateTime, nullable=True),
      Column("comments", LargeBinary, nullable=True),
      Column(
         "createdate",
         DateTime,
         nullable=False,
         server_default=text("'0000-00-00 00:00:00'"),
      ),
      Column(
         "modifydate",
         DateTime,
         nullable=False,
         server_default=text("'0000-00-00 00:00:00'"),
      ),
      Column("createuser", BigInteger, nullable=False, server_default=text("'0'")),
      Column("modifyuser", BigInteger, nullable=False, server_default=text("'0'")),
      Column("editor", String(100), nullable=False, server_default=text("''")),
      Column("realeditor", String(100), nullable=False, server_default=text("''")),
      Column("lastqcheck", DateTime, nullable=True, index=True),
      Column("description", String(128), nullable=True),
      Column("lastknownbossemail", LargeBinary, nullable=True),
      Column("is_org", Integer, nullable=True, server_default=text("'0'")),
      Column("is_line", Integer, nullable=True, server_default=text("'0'")),
      Column("is_depart", Integer, nullable=True, server_default=text("'0'")),
      Column("is_resort", Integer, nullable=True, server_default=text("'0'")),
      Column("is_team", Integer, nullable=True, server_default=text("'0'")),
      Column("is_orggroup", Integer, nullable=True, server_default=text("'0'")),
      Column("additional", Text, nullable=True),
      Column("grppresentation", Text, nullable=True),
      Column("ext_refid1", String(40), nullable=True, index=True),
      Column("ext_refid2", String(80), nullable=True, index=True),
      Column("is_projectgrp", Integer, nullable=True, server_default=text("'0'")),
      Column("accarea", String(20), nullable=True),
      Column("sisnumber", String(20), nullable=True),
      Column("nsin", String(20), nullable=True),
      Column("isin", String(20), nullable=True),
      Column("comregnum", String(20), nullable=True),
      Column("srcurl", String(256), nullable=True),
      Column("lorgchangedt", DateTime, nullable=True),
      Column("lrecertreqdt", DateTime, nullable=True),
      Column("lrecertdt", DateTime, nullable=True),
      Column("lrecertuser", BigInteger, nullable=True),
      Column("lrecertreqnotify", DateTime, nullable=True),
      *localSQLalchemy.defaultSourceTableColumns(),
      # --- Unique Constraints ---
      UniqueConstraint("fullname", name="fullname"),
      # --- Composite / Multi-Column Indexes ---
      Index("name", "name", "cistatus"),
      extend_existing=True,
   )

